---
title: "Untitled"
author: "Iwen Su"
date: "March 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages

```{r message=FALSE, warning=FALSE}

library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)
library(corrplot)

```

### Read in data: column graph of Texas oil spills

```{r}

oil_spills <- read_csv("oil_spills.csv")

df <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` < 2017) %>% 
  group_by(`Accident Year`) %>% 
  summarise(Loss = sum(`Net Loss (Barrels)`))

colnames(df) <- c("Year","Loss")

ggplot(df, aes(x = Year, y = Loss)) +
  geom_col()

```

### Leaflet plot of spill locations in TX in 2016

```{r}

df_loc <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` == 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc) <- c("latitude", "longitude", "net_loss")

# Convert to simple features since R doesn't know this data frame is spatial data yet! But we have lat-lon data
class(df_loc)

# order of longitude and longitude columns must be as follows
oil_sf <- st_as_sf(df_loc, coords = c("longitude","latitude"), crs = 4326)
class(oil_sf)

leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()

```

